version: '3'
services:
  db:
    container_name: laravel_db
    build: ./db/
    image: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: d_mason
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/usr/local/var/mysql
    networks:
      - webnet
  app:
    container_name: laravel_app
    build: ./app/
    image: laravel_app
    ports:
      - 80:8000
    links:
      - db
    volumes:
      - ../portfolio:/var/www/html/laravel
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
